### ISSUE TITLE
Grafana 

### ISSUE THREAD

**Issue by Flarak** [georou/grafana-selinux#1]
Hi,

I found some issues with the policy when playing around with Grafana and SELINUX,
but was able to solve/circumvent the issues.

My configuration uses Grafana with icinga2/icingaweb and with influxdb as backend; 
Grafana sesssion/dashboards/settings are stored in mysql.

My modifications to your policy 1.0.0.0:
gen_require(`
	type httpd_t;
	type mysqld_port_t;
	type devlog_t;
	type fonts_t;
	type fs_t;
	type ld_so_cache_t;
	type locale_t;
	type usr_t;
	type unreserved_port_t;
	class file entrypoint;
')
..
## MG: 00 - fixes connection with mysql
allow grafanad_t kernel_t:system module_request;
allow grafanad_t mysqld_port_t:tcp_socket name_connect;
allow grafanad_t self:netlink_route_socket { bind create getattr nlmsg_read };
## MG: 01 - fixes grafana logging to syslog
allow grafanad_t devlog_t:sock_file write;
## MG: 02 - phantomjs binary execution 
# note: /usr/share/grafana/tools/phantomjs/phantomjs needs relabeling 
allow grafanad_t usr_t:file execute;
allow grafanad_t fonts_t:file execute;
allow grafanad_t grafanad_port_t:tcp_socket name_connect;
allow grafanad_t fs_t:filesystem getattr;
allow grafanad_t ld_so_cache_t:file execute;
allow grafanad_t locale_t:file execute;
allow grafanad_t self:process { execmem setrlimit };
## MG: 03 - grafana connect to itself 
allow grafanad_t unreserved_port_t:tcp_socket name_connect;
##

If you need further info about my setting -please contact me.

regards

MG

**Comment by georou** [comment]
Hi MG, I appreciate you taking the time to drop by with these suggestions.

I've got a few questions and suggestions for your if you have extra time. Just firstly, what OS are you using?

## MG 00:
- allow grafanad_t kernel_t:system module_request; - What kernel module is grafana trying to load? If you could paste in the full AVC message that would help too.

- allow grafanad_t self:netlink_route_socket { bind create getattr nlmsg_read }; - A suggestion, you might be better off using the create_netlink_socket_perms macro.

## MG 01:
For logging directly to 'syslog', I would use the logging_send_syslog_msg(grafanad_t) interface as it is more complete for the access it might need(now and in the future). [More info here](https://github.com/fedora-selinux/selinux-policy/blob/rawhide/policy/modules/system/logging.if#L631) 

## MG 03 - grafana connect to itself:
I'm assuming this is an old AVC entry after you changed something? Once you add in the `<allow grafanad_t grafanad_port_t:tcp_socket name_connect;>` it should be fine. Or this is the port you're trying to connect to InfluxDB on? 8086?

If it's the latter, know that you're also giving grafana access to a large port range (>1024 ports). It's up to you how secure this is for your system. I'm not clear on your SELinux knowledge, it's probably worth creating a policy for InfluxDB and allowing grafana specific port access instead.


The rest between MG 02-03, all seem to be related to using phantomjs to render out a PNG of a panel. I haven't used that feature before as this policy is designed as a starting point to get all the basics working. I'll consider the phantomjs part but I'm a little hesitant since it requires execmem and execute on usr_t files (for fonts). If you're comfortable implementing them, you just need to consider your use case and threat model.

Thanks again for the heads up. I'll add in the bits that are helpful to the base policy.

**Comment by georou** [comment]
MG, I had some time this Friday to read more into phantomjs and the Direct Link Share in grafana.

From what I've read about phantomjs, and allowing grafana to execute memory, it's probably not wise to allow it. Phantomjs has it's own problems with malicious use and now compounded with not being actively developed. Allowing execmem could open up security vectors such as buffer overflow attacks.

It also seems development of phantomjs has been **stopped**. From [this closed ticket](https://github.com/grafana/grafana/issues/11078) the grafana dev team are moving to 'headless chrome/puppeteer' instead. Looks like phantomjs will also be removed in future grafana versions.

Looks like waiting to see what the devs will do is a good option on this one. Current discussion:[https://github.com/grafana/grafana/issues/13802](github)
